nmi_num:				.res 1
control_pad:			.res 1
control_old:			.res 1
no_control:				.res 1
bg_addy_offset:			.res 1
round_offset:			.res 1
nametable_select:		.res 1
nametable:				.res 1
nmi_offset:				.res 1
hscroll:				.res 1
time_wait:				.res 1
lay_tiles:				.res 1
reg2000_save:			.res 1
reg2001_save:			.res 1
temp:					.res 1

loop_pointer:			.res 2
line00:					.res 2
line01:					.res 2
line02:					.res 2
line03:					.res 2
line04:					.res 2
line05:					.res 2
line06:					.res 2
line07:					.res 2
line08:					.res 2
line09:					.res 2
line10:					.res 2
line11:					.res 2
line12:					.res 2
line13:					.res 2
line14:					.res 2
line15:					.res 2
line16:					.res 2
maze_addy_sprites_y:	.res 2
maze_addy_sprites_x:	.res 2
maze_addy_pos:			.res 2
tile_find_first:		.res 2
tile_find_second:		.res 2
tile_find_third:		.res 2

tile_on:				.res 1
tile_off:				.res 1
tile_detect:			.res 1
move_snail:				.res 1
snail_count:			.res 1
snail_y_pos:			.res 1
snail_x_pos:			.res 1
goal_y_pos:				.res 1
goal_x_pos:				.res 1
head_sprite_y:			.res 1
snail_sprite_y:			.res 1
flag1_sprite_y:			.res 1
flag2_sprite_y:			.res 1
flag3_sprite_y:			.res 1
flag4_sprite_y:			.res 1
flag5_sprite_y:			.res 1
start_sprite_y:			.res 1
goal_sprite_y:			.res 1
head_sprite_x:			.res 1
snail_sprite_x:			.res 1
flag1_sprite_x:			.res 1
flag2_sprite_x:			.res 1
flag3_sprite_x:			.res 1
flag4_sprite_x:			.res 1
flag5_sprite_x:			.res 1
start_sprite_x:			.res 1
goal_sprite_x:			.res 1
one_second:				.res 1
big_seconds:			.res 1
game_beaten:			.res 1
anim_ticker:			.res 1
anim_offset:			.res 1
reset_game:				.res 1
no_sprite0:				.res 1
splash_offset:			.res 1
splash_count:			.res 1
do_message:				.res 1
message_addy:			.res 2
message_offset:			.res 1
message_bg_addy_lo:		.res 1
message_bg_addy_hi:		.res 1
message_present:		.res 1

sly_row1_tile:			.res 1
sly_row1_addy:			.res 1
sly_row2_tile:			.res 1
sly_row2_addy:			.res 1
sly_row3_tile:			.res 1
sly_row3_addy:			.res 1
sly_row4_tile:			.res 1
sly_row4_addy:			.res 1
do_splash:				.res 1
